steps:
  # Activities
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-central2-docker.pkg.dev/trackmyfit-459021/activities', '-f', 'backend/apps/activities/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/trackmyfit-459021/activities']
  # Auth
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-central2-docker.pkg.dev/trackmyfit-459021/auth', '-f', 'backend/apps/auth/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/trackmyfit-459021/auth']
options:
  logging: CLOUD_LOGGING_ONLY