services:
  activities:
    build:
      context: ./backend
      dockerfile: ./apps/activities/Dockerfile
      target: development
    command: pnpm run start:dev activities
    develop:
      watch:
        - action: sync
          path: ./apps/activities
          target: /usr/src/app/apps/activities
          ignore:
            - node_modules/
    env_file:
      - ./backend/apps/activities/.env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 3001:3001
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--spider',
          '-q',
          'http://localhost:3001/activities/health',
        ]
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - /usr/src/app/node_modules
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: development
      args:
        - NEXT_PUBLIC_API_URL=http://activities:3001
    command: pnpm dev
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
    ports:
      - 3000:3000
    depends_on:
      activities:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://activities:3001
    volumes:
      - /app/node_modules
volumes:
  postgres_data:
