apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: activities
  name: activities
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activities
  template:
    metadata:
      labels:
        app: activities
    spec:
      containers:
      - image: europe-central2-docker.pkg.dev/trackmyfit-459021/activities/production
        name: activities
        ports:
          - containerPort: 3001
        env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: postgres
                key: host
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-password
                key: password
          - name: POSTGRES_PORT
            value: '5432'
          - name: POSTGRES_USER
            value: 'postgres'
          - name: POSTGRES_DB
            value: 'trackmyfit'
          - name: PORT
            value: '3001'
          - name: RABBITMQ_URI
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: uri


