apiVersion: v1
kind: Service
metadata:
  labels:
    app: activities
  name: activities
spec:
  ports:
  - name: "http"
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: activities
  type: NodePort
