apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - image: europe-central2-docker.pkg.dev/trackmyfit-459021/auth/production
        name: auth
        env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: postgres
                key: host
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-password
                key: password
          - name: POSTGRES_PORT
            value: '5432'
          - name: POSTGRES_USER
            value: 'postgres'
          - name: POSTGRES_DB
            value: 'trackmyfit'
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt
                key: jwtSecret 
          - name: JWT_EXPIRATION
            value: '3600000'
          - name: PORT
            value: '3002'
          - name: RABBITMQ_URI
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: uri
        ports:
          - containerPort: 3002

